name: Lint Markdown

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.jsonc'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.jsonc'
      - '.github/workflows/markdownlint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Run Markdownlint
    runs-on: ubuntu-latest
    steps:
      # ---
      - name: Checkout repository
        uses: actions/checkout@v7
      # ---
      - name: Run markdownlint-cli2
        run: |
          npx markdownlint-cli2 "**/*.md"
